### ISSUE TITLE
Reset context failed after completed request

### ISSUE THREAD

**Issue by hargueta** [CSUMB-SP17-CST499/PLex-Chatbot#43]
reset context failed
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }

**Comment by yarelyc** [comment]
No longer resetting context. :) thanks!
